- id: check-unused-vars
  name: Check Unused Variables
  description: This hook checks unused variables in terraform code then removes them
  entry: terraform-check-unused-variables
  language: python
