repos:
-   repo: https://github.com/mcole18/terraform-check-unused-variables.git
    rev: v0.2.1-alpha
    hooks:
    -   id: check-unused-vars
        args: [-v]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
