name: CI

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
        working-directory: ./

    steps:

# semantic version
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
    
# python
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
            python-version: 3.9.7
    
      - name: Install pip
        run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt



#- name: Lint with flake8
#run: |
#pip install flake8
#flake8

#- name: Coverage report
#working-directory: ./
#run: |
#pip install coverage
#coverage run manage.py test
#coverage report

#- name: Run tests
#working-directory: ./tests
#run: python3 

